Insert into theme(libelle) values 
("Diagnostic et identification des critères du club"), 
("Analyse systémique de l'environnement et méthodologique de mise en oeuvre du projet"), 
("Action solidaires et innovantes"), 
("Financements"), 
("Outils et documentation"), 
("Valoriser et communiquer sur le projet"), 
("Création - Obligations légales"), 
("Gestion du personnel, de la structure et des conflits"), 
("Relations internes, externes et avec le comité départemental, la ligue, et la fédération"), 
("Conventions"), 
("Partenariats"),
("Logiciel FFE de gestion des compétitions (présentation et formation"),
("Présentation du document 'L'arbitrage en images'"),
("Plaquette 'Guide projet du club'"),
("Labellisation du club"),
("Aménagement des équipements"),
("Assurances"),
("Observations et analyses sur l'encadrement actuel"), 
("Proposition de novueaux schémas d'organisation"), 
("Profils types et pratiques innonvantes"), 
("Critères et seuils nécessaires à la pérennité de l'emploi"), 
("Exercice du métider d'enseignant (avantages et inconvénients)"), 
("Présentation"),
("Fonctionnement"),
("Objectifs"),
("Nouveaux diplômes"),
("Financements"),
("Les enjeux climatiques, énergétiques et économiques"),
("Sport et développement durable"),
("Démarche fédérale"),
("Echange");


insert into themesparatelier(idatelier, idtheme) values
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(2, 7),
(2, 8),
(2, 9),
(2, 10),
(2, 11),
(3, 12),
(3, 13),
(3, 14),
(3, 15),
(3, 16),
(3, 17),
(4, 18),
(4, 19),
(4, 20),
(4, 21),
(4, 22),
(5, 23),
(5, 24),
(5, 25),
(5, 26),
(5, 27),
(6, 28),
(6, 29),
(6, 30),
(6, 31);


insert into restauration (typesrepas, daterestauration) values 
('midi', '2021-09-14 00:00:00'),
('soir', '2021-09-14 00:00:00'),
('midi', '2021-09-15 00:00:00');